name: emotional_bakery
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1 # 상태 관리용
  audioplayers: ^5.2.1 # BGM, 효과음용
  json_annotation: ^4.8.1 # JSON 파싱용

  cupertino_icons: ^1.0.8
  flame: ^1.37.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/data/

#  fonts:
#    - family: 머시기 머시기
#     fonts:
#       - asset: assets/fonts/머시기.ttf
