name: emotional_bakery
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1 # 상태 관리용
  audioplayers: ^5.2.1 # BGM, 효과음용
  json_annotation: ^4.8.1 # JSON 파싱용

  cupertino_icons: ^1.0.8
  flame: ^1.37.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/data/
    - assets/data/chapter1/
    - assets/data/chapter3/
    - assets/data/shared/
    - assets/lines/
    - assets/lines/chapter1/
    - assets/lines/chapter2/
    - assets/lines/chapter3/

  fonts:
    - family: SCDream
      fonts:
        - asset: assets/fonts/SCDream1.otf
          weight: 100
        - asset: assets/fonts/SCDream2.otf
          weight: 200
        - asset: assets/fonts/SCDream3.otf
          weight: 300
        - asset: assets/fonts/SCDream4.otf
          weight: 400
        - asset: assets/fonts/SCDream5.otf
          weight: 500
        - asset: assets/fonts/SCDream6.otf
          weight: 600
        - asset: assets/fonts/SCDream7.otf
          weight: 700
        - asset: assets/fonts/SCDream8.otf
          weight: 800
        - asset: assets/fonts/SCDream9.otf
          weight: 900
